### PR TITLE
Reorder ssclj classpath

### PR DESCRIPTION
**Pull request by st**
`resources`folder must have precedence over `ssclj.jar`
Connected to #741

### CODE REVIEW

**Comment by loomis** [comment]
What is (are) the conflicting file(s) when the classpath is in the wrong order?

**Comment by loomis** [comment]
There seem to be a large number of files that probably should not be in the ssclj service jar file:
```
auth_privkey.pem
auth_pubkey.pem
config-hsqldb-mem.edn
config-hsqldb.edn
es-build.properties
example-event.json
project.clj
sqlite.edn
```

And these file should probably be moved to a specific namespace or incorporated directly into the files that read them:
```
filter-grammar.txt
mapping-not-analyzed.json
```

Any comments on removing/including the above files?

**Comment by st** [comment]
```auth_privkey.pem
auth_pubkey.pem
```
These 2 files are actually used by auth service (served by ssclj server)
(can be overriden after installation: http://ssdocs.sixsq.com/en/latest/administrator_guide/maintenance.html?highlight=pem#authentication-keys)
```
project.clj
```
For people who want to use leiningen, this is usefull.

Could not find this file in project:
```
es-build.properties
```
to be removed:
```
config-hsqldb-mem.edn
config-hsqldb.edn
example-event.json
sqlite.edn
```

**Comment by loomis** [comment]
I've removed unused files and dependencies from the repository and/or jar file.  Certificates were removed from the jar and moved to the RPM as configuration files.  @st review the changes to make sure nothing has been broken, if not, the PR can be merged.

**Pull request merged**
