### PR TITLE
fix comparator for price ordering

### PR DESCRIPTION
**Pull request by loomis**
Connected to sixsq/SlipStreamPricing#41.

### CODE REVIEW

**Comment by konstan** [comment]
It compiles and unit tests work.  As part of the validation, 

1. should I just push the jar with this change only to nuv.la and check if `java.lang.IllegalArgumentException: Comparison method violates its general contract!` is no longer thrown?  

2. Or I can create a system test for PRS with service catalog pre-populated with the service offers from nuv.la.  This will be an extension of nuv.la reference configuration that we have. That would actually work as a pre-prod test (on the data level).  Too heavy?  Do we need it now?

**Comment by loomis** [comment]
I don't think that we need a system test for this at the moment.  Pushing it to Nuvla is reasonable.

**Comment by konstan** [comment]
OK.  I'll validate this on nuv.la then.

**Comment by konstan** [comment]
Tested on nuv.la.  Everything works.  Merging.

**Pull request merged**
