### PR TITLE
Fix #265 improve logging

### LINKED ISSUE #265: Improve logging
- [x] Improve the logging format.
- [x] Allow to set a log level under INFO.

### PR DESCRIPTION
**Pull request by schaubl**
Corresponding issue #265 

@st @loomis @mebster @konstan @rbf : Can you give your opinion about the new log format ?
And if one of you can review other changes of this pull request.

The new log format look like this:
```bash
03/11/15 00:49:07.989 CET INFO com.sixsq.slipstream.util.Logger info No users to collect for online users 
03/11/15 22:49:08.481 CET INFO com.sixsq.slipstream.util.Logger info Inserting collect request for [sixsq/Exoscale] 1426117748481  after timeout 150832 
03/11/15 22:49:08.482 CET INFO com.sixsq.slipstream.util.Logger info executing collect request for sixsq and Exoscale 
03/11/15 22:49:43.434 CET INFO com.sixsq.slipstream.connector.Collector logTiming [super/Exoscale] (666 ms) : describe VMs done. 
03/11/15 22:49:43.437 CET INFO com.sixsq.slipstream.connector.Collector logTiming [super/Exoscale] (3 ms) : populate DB VMs done.
03/11/15 22:57:46.207 CET INFO com.sixsq.slipstream.util.ProcessUtils execGetOutputAsArray Calling: sh -c /usr/bin/nuvlabox-describe-instances  -t 60 --username 'ssuser' --endpoint 'https://nuvlabox:2634/one-proxy/xmlrpc'   
03/11/15 22:57:46.667 CET WARNING com.sixsq.slipstream.util.ProcessUtils execGetOutputAsArray Error executing: sh -c /usr/bin/nuvlabox-describe-instances  -t 60 --username 'ssuser' --endpoint 'https://nuvlabox:2634/one-proxy/xmlrpc'  . With exit code = 2 and stdout: <ProtocolError for ssuser@nuvlabox:2634/one-proxy/pswd/xmlrpc: 401 Unauthorized> and stderr:  
03/11/15 22:57:46.669 CET WARNING com.sixsq.slipstream.connector.Collector describeInstances Failed contacting cloud [SlipStreamRuntimeException]: [nuvlabox/nuvlabox] with '<ProtocolError for ssuser:@nuvlabox:2634/one-proxy/pswd/xmlrpc: 401 Unauthorized>'```

### CODE REVIEW

**Comment by st** [comment]
The new log format is a big improvement.
2 remarks:

The date/time format could use ISO 8601 one (it looks like that: 2015-03-12T09:45:23.944Z). This format is used by Clojure resources (Event).
Clojure wrapper needs to be adapted (suppress redundant display of level).

**Comment by loomis** [comment]
I agree with switching to the ISO format for the date.  This makes it easier to split the message on spaces and to sort the result.  I would suggest that we consistently use GMT everywhere (with 'Z' abbreviation) rather than using an explicit timezone as is permitted by the ISO format.

**Comment by schaubl** [comment]
Ok, I will change to the ISO 8601. FYI I will have to create it manually because this format is only available for date but not for time (see http://docs.oracle.com/javase/7/docs/api/java/util/Formatter.html#dt).

**Comment by schaubl** [comment]
Below is the new log format
```bash
2015-03-12T11:38:47.176+0100 WARNING com.sixsq.slipstream.util.Logger warning Server started 
 2015-03-12T11:38:47.177+0100 SEVERE com.sixsq.slipstream.util.Logger severe Server started 
 2015-03-12T11:38:47.348+0100 INFO com.sixsq.slipstream.util.Logger info No users to collect for online users 
 2015-03-12T11:38:47.434+0100 INFO com.sixsq.slipstream.util.Logger info Inserting collect request for [Bob/nuvlabox] 1426156727434  after timeout 0 
 2015-03-12T11:38:47.435+0100 INFO com.sixsq.slipstream.util.Logger info executing collect request for Bob and nuvlabox 
 2015-03-12T11:38:47.654+0100 INFO org.restlet.ext.httpclient.HttpClientHelper start Starting the Apache HTTP client 
```
Unfortunately it doesn't respect completely the ISO 8601 because there is no `:` between hour and minutes of the GMT offset.

**Comment by schaubl** [comment]
@st : Do you want to review this pull request ?

**Pull request merged**
