### PR TITLE
multiple indexes, wip

### PR DESCRIPTION
**Pull request by 0xbase12**

### CODE REVIEW

**Comment by schaubl** [comment]
This will have to be updated accordingly:
https://github.com/slipstream/SlipStreamJobEngine/blob/v3.48/job/src/slipstream/job/actions/jobs_cleanup.py#L23

**Comment by konstan** [comment]
@loomis This PR compiles and all tests pass for me on 3.51-SNAPSHOT with slipstream-parent defining ES v6.2.4.

Corresponding PRs in Connectors
https://github.com/slipstream/SlipStreamConnectors/pull/219
https://github.com/SixSq/SlipStreamConnectors/pull/162

**Comment by konstan** [comment]
PR in slipstream-parent
https://github.com/slipstream/SlipStreamParent/pull/1

**Comment by konstan** [comment]
@loomis The thing I didn't do yet is to start SS/CIMI on my dev machine.  I'll try to do this today.

**Pull request merged**
