### PR TITLE
build arm image

### PR DESCRIPTION
**Pull request by cjdcordeiro**

### CODE REVIEW

**Comment by cjdcordeiro** [comment]
connected to https://github.com/mF2C/cimi/issues/4

**Comment by cjdcordeiro** [comment]
there's `buildArg` which might simplify this code duplication, but the image naming and base images would still be a problem

**Comment by loomis** [comment]
@cjdcordeiro You should verify that the consolidated assembly descriptor works as expected for you.  It looked OK to me.

**Comment by cjdcordeiro** [comment]
lgtm

**Pull request merged**
