### PR TITLE
Point to java from JRE version which gets defined at the package build time

### PR DESCRIPTION
**Pull request by konstan**
Connected to #416

### CODE REVIEW

**Comment by loomis** [comment]
The copy and replacement of a variable in a file can be done much more efficiently, portably, and succinctly by using the resources plugin rather than `cp`/`sed` through the exec plugin.  You should only need to move the file to the `resources` area, add the file to the list of filtered files, and change the value to replace with `${your variable}` in the file.

**Comment by konstan** [comment]
Thanks!  Never used it :-/  Trying now.

**Comment by konstan** [comment]
@loomis Just pushed the changes with using `resources` plugin (very convenient! :-)).  Please check.

**Comment by loomis** [comment]
Looks OK to me.  Files are properly changed and included in the packages.  Merging...

**Pull request merged**
