### PR TITLE
add fields to module for data format/protocol matching

### PR DESCRIPTION
**Pull request by loomis**
Connected to #1696 
Connected to #1697

### CODE REVIEW

**Comment by loomis** [comment]
This PR adds two optional fields to the `module` resource: `acceptContentTypes` and `acceptProtocols`.  These  identify the data formats and data access protocols that are supported by the module.  

 - The implementation adds this to the core `module` resource.  Consequently, these fields are shared for all versions of the module.  This was done to facilitate the queries of the modules for specific data types/protocols.  Note that these fields are also allowed on image module, although they don't make much sense there. 
 - Modules that accept data must define both of these fields.  For modules that can analyze any data format, then the MIME type `application/octet-stream` should be used. A module must always list a concrete set of protocols.
 - The values for `acceptContentTypes` must be syntactically valid MIME type values.  They do not need to be officially registered values.  That is, values such as `application/x-my-special-type` can be used, although officially registered values are preferred if they are applicable.
 - The values for `acceptProtocols` are any valid token (sequence of characters without whitespace). The concrete values are agreed conventions between the producer and consumer of the data.  Values such as 'http+s3' or 'posix+nfs' are recommended.
 - With this schema, it is not possible to denote that a module requires multiple data formats simultaneously.

**Comment by loomis** [comment]
@konstan Please review this PR along with the comments on the implementation.

**Comment by loomis** [comment]
@konstan 

> Extra list dataRequireContentTypes or dataAcceptContentTypes as a map with :contentTypeName <"req" | "opt">?

How is that going to work in the deployment workflow?

**Comment by loomis** [comment]
@konstan I've updated the attribute names.  Waiting on feedback for the required/optional before making any changes for that.

**Comment by konstan** [comment]
@loomis After giving it a bit of thought - it's getting unnecessarily complex for the initial implementation. Lets not do this now.

**Pull request merged**
