### PR TITLE
Issue #170 - Added the ability to redefine values of input parameters when running an image.

### LINKED ISSUE #170: Allow users to redefine "input parameters" for "Simple Run"

### PR DESCRIPTION
**Pull request by schaubl**
Fix #170.

### CODE REVIEW

**Comment by schaubl** [comment]
Changes on the file `SimpleRunFactory.java` are not part of this pull request.
They are part of the PR #299.

**Comment by schaubl** [comment]
@loomis : Can you review it ?

**Comment by loomis** [comment]
The changes look OK to me.

**Comment by schaubl** [comment]
Ok, I solved conflicts.
So I will merge it.

**Pull request merged**
