### PR TITLE
don't define edition in build.boot and provide it from pom.xml

### PR DESCRIPTION
**Pull request by konstan**
Connected to #771

### CODE REVIEW

**Comment by konstan** [comment]
@loomis If the change is approved and merged, the same change should be done in https://github.com/slipstream/SlipStreamClientAPI/tree/master/jar

**Comment by loomis** [comment]
But by making this change, it means that every time `boot` is used from the command line, the correct value for the edition will have to be set explicitly to pull in the right clojure client API.  So every `boot test` will become `boot test --set-env edition=community`, etc.  I'm not convinced this is an improvement.

**Comment by konstan** [comment]
Then, we can to define `edition` in `sixsq/boot-deputil` (or similar).  OK?

**Comment by loomis** [comment]
The task for managing dependencies isn't well-suited to handling other parts of the global configuration.  Ideally you'd like to define a function that could be used to set the value for "edition".  Something like this could be achieve with the `boot.profile`, but the code would then need to be duplicated to every repository.  I'm wondering whether this really needs to be solved through automation/global configuration.  There are only two values for this and once set correctly in the various repositories, git does a good job of not overwriting the value.

**Comment by loomis** [comment]
The build file must always reference some source file that contains the correct configuration for the edition.  In this case, either we have to hardcode that reference or hardcode the name of the edition.  For the dependencies, there is a gain by using the reference because there are a large number of values.  For the edition, it don't see the gain as this is a single value.  I'd propose closing this PR as it doesn't (IMO) bring any real benefit.

**Comment by konstan** [comment]
Agreed and closing.

**Pull request closed without merging**
