### PR TITLE
dynamically refresh service configuration on Configuration singleton from backend

### PR DESCRIPTION
**Pull request by konstan**
Connected to #1456

### CODE REVIEW

**Comment by konstan** [comment]
@loomis The PR is ready for validation.

**Comment by konstan** [comment]
@loomis this commit disables rendering of system configuration link in drop down menu
https://github.com/slipstream/SlipStreamUI/commit/594f2e84e713826cf24864102adde7fc1e6014a5

**Comment by konstan** [comment]
@loomis This is the related PR for nuvlabox connector https://github.com/SixSq/SlipStreamConnectors/pull/157

**Comment by loomis** [comment]
Build worked and demo was done.

**Pull request merged**
